services:
  container5:
    image: alpine
    container_name: container5
    hostname: container5
    ports:
      - "8090:8090"
    depends_on:
      - "syslogserver"
    command: sh -c "while true; do echo hello world; sleep 10; done"
    logging:
      driver: "syslog"
      options:
        syslog-address: tcp://0.0.0.0:514
        tag: "docker/{{.Name}}"
  container6:
    image: alpine
    container_name: container6
    hostname: container6
    ports:
      - "8092:8092"
    depends_on:
      - "syslogserver"
    command: sh -c "while true; do echo hello world hahaha; sleep 10; done"
    logging:
      driver: "syslog"
      options:
        syslog-address: tcp://0.0.0.0:514
        tag: "docker/{{.Name}}"
  syslogserver:
    build:
      context: .
      dockerfile: Dockerfile.rsyslog
    container_name: syslogserver
    hostname: syslogserver
    ports:
      - "514:514"
